{{ config(
    materialized='table',
    engine='MergeTree()',
    order_by='currency_code'
) }}

SELECT 1 AS currency_id, 'AUD' AS currency_code, 'AUSTRALIAN DOLLAR' AS currency_name
UNION ALL SELECT 2, 'CAD', 'CANADIAN DOLLAR'
UNION ALL SELECT 3, 'CHF', 'SWISS FRANC'
UNION ALL SELECT 4, 'CNY', 'YUAN RENMINBI'
UNION ALL SELECT 5, 'DKK', 'DANISH KRONE'
UNION ALL SELECT 6, 'EUR', 'EURO'
UNION ALL SELECT 7, 'GBP', 'POUND STERLING'
UNION ALL SELECT 8, 'HKD', 'HONGKONG DOLLAR'
UNION ALL SELECT 9, 'INR', 'INDIAN RUPEE'
UNION ALL SELECT 10, 'JPY', 'YEN'
UNION ALL SELECT 11, 'KRW', 'KOREAN WON'
UNION ALL SELECT 12, 'KWD', 'KUWAITI DINAR'
UNION ALL SELECT 13, 'MYR', 'MALAYSIAN RINGGIT'
UNION ALL SELECT 14, 'NOK', 'NORWEGIAN KRONER'
UNION ALL SELECT 15, 'RUB', 'RUSSIAN RUBLE'
UNION ALL SELECT 16, 'SAR', 'SAUDI RIAL'
UNION ALL SELECT 17, 'SEK', 'SWEDISH KRONA'
UNION ALL SELECT 18, 'SGD', 'SINGAPORE DOLLAR'
UNION ALL SELECT 19, 'THB', 'THAILAND BAHT'
UNION ALL SELECT 20, 'USD', 'US DOLLAR'
UNION ALL SELECT 21, 'VND', 'VIETNAM DONG'