version: 1
sources:
  - name: raw_data
    database: raw
    tables:
      - name: sjc_raw
        description: "Raw SJC table ingested from Kafka Connect"
      - name: goldprice_raw
        description: Raw Goldprice table ingested from Kafka Connect"
      - name: binance_raw
        description: Raw Binance table ingested from Kafka Connect"
      - name: vcb_raw
        description: Raw VCB exchange rate table ingested from Kafka Connect"
  - name: staging
    database: staging_dev
    tables:
      - name: stg_goldprice
      - name: stg_vcb
      - name: stg_binance
      - name: stg_sjc

  - name: silver
    database: silver
    tables:
      - name: silver_gold_exchange
      - name: dim_date
      - name: dim_currency
      - name: dim_product
      - name: dict_dim_product
      - name: dict_dim_currency
